#!/bin/bash
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_2.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_2/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_2/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_2/ --model ./checkpoint/Subset2_epoch72.pth
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_12.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_12/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_12/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_12/ --model ./checkpoint/Subset2_epoch72.pth
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_9.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_9/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_9/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_9/ --model ./checkpoint/Subset2_epoch72.pth
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_13.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_13/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_13/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_13/ --model ./checkpoint/Subset2_epoch72.pth
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_1.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_1/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_1/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_1/ --model ./checkpoint/Subset2_epoch72.pth
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_8.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_8/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_8/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_8/ --model ./checkpoint/Subset2_epoch72.pth
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_3.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_3/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_3/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_3/ --model ./checkpoint/Subset2_epoch72.pth
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_11.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_11/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_11/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_11/ --model ./checkpoint/Subset2_epoch72.pth
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_4.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_4/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_4/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_4/ --model ./checkpoint/Subset2_epoch72.pth
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_6.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_6/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_6/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_6/ --model ./checkpoint/Subset2_epoch72.pth
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_15.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_15/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_15/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_15/ --model ./checkpoint/Subset2_epoch72.pth
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_5.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_5/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_5/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_5/ --model ./checkpoint/Subset2_epoch72.pth
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_7.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_7/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_7/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_7/ --model ./checkpoint/Subset2_epoch72.pth
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_16.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_16/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_16/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_16/ --model ./checkpoint/Subset2_epoch72.pth
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_10.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_10/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_10/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_10/ --model ./checkpoint/Subset2_epoch72.pth
python test_evaluate.py --i /data/acharl15/gleason_grading/test_folder/Subset2_Test_14.tiff --annotation /data/acharl15/gleason_grading/test_folder/Subset2_Test_annotation/Subset2_Test_14/ --output_patch_folder /data/acharl15/gleason_grading/test_folder/patch/Subset2_Test_14/ --output_result_folder /data/acharl15/gleason_grading/test_folder/result/Subset2_Test_14/ --model ./checkpoint/Subset2_epoch72.pth
