#!/bin/bash
python evaluate.py --i Subset1_Test_40
python evaluate.py --i Subset1_Test_17
python evaluate.py --i Subset1_Test_31
python evaluate.py --i Subset1_Test_26
python evaluate.py --i Subset1_Test_6
python evaluate.py --i Subset1_Test_41
python evaluate.py --i Subset1_Test_21
python evaluate.py --i Subset1_Test_12
python evaluate.py --i Subset1_Test_13
python evaluate.py --i Subset1_Test_18
python evaluate.py --i Subset1_Test_27
python evaluate.py --i Subset1_Test_38
python evaluate.py --i Subset1_Test_33
python evaluate.py --i Subset1_Test_44
python evaluate.py --i Subset1_Test_39
python evaluate.py --i Subset1_Test_9
python evaluate.py --i Subset1_Test_11
python evaluate.py --i Subset1_Test_2
python evaluate.py --i Subset1_Test_7
python evaluate.py --i Subset1_Test_45
python evaluate.py --i Subset1_Test_10
python evaluate.py --i Subset1_Test_37
python evaluate.py --i Subset1_Test_19
python evaluate.py --i Subset1_Test_3
python evaluate.py --i Subset1_Test_8
python evaluate.py --i Subset1_Test_1
python evaluate.py --i Subset1_Test_28
python evaluate.py --i Subset1_Test_29
python evaluate.py --i Subset1_Test_22
python evaluate.py --i Subset1_Test_23
python evaluate.py --i Subset1_Test_5
python evaluate.py --i Subset1_Test_34
python evaluate.py --i Subset1_Test_20
python evaluate.py --i Subset1_Test_14
python evaluate.py --i Subset1_Test_43
python evaluate.py --i Subset1_Test_15
python evaluate.py --i Subset1_Test_16
python evaluate.py --i Subset1_Test_35
python evaluate.py --i Subset1_Test_24
python evaluate.py --i Subset1_Test_30
python evaluate.py --i Subset1_Test_32
python evaluate.py --i Subset1_Test_36
python evaluate.py --i Subset1_Test_4
python evaluate.py --i Subset1_Test_25
python evaluate.py --i Subset1_Test_42
