#!/bin/bash
python preprocess_img.py --i Subset2_Train_14.tiff --annotation Subset2_Train_14 --output Subset2_Train_14
python preprocess_img.py --i Subset2_Train_34.tiff --annotation Subset2_Train_34 --output Subset2_Train_34
python preprocess_img.py --i Subset2_Train_22.tiff --annotation Subset2_Train_22 --output Subset2_Train_22
python preprocess_img.py --i Subset2_Train_18.tiff --annotation Subset2_Train_18 --output Subset2_Train_18
python preprocess_img.py --i Subset2_Train_19.tiff --annotation Subset2_Train_19 --output Subset2_Train_19
python preprocess_img.py --i Subset2_Train_23.tiff --annotation Subset2_Train_23 --output Subset2_Train_23
python preprocess_img.py --i Subset2_Train_35.tiff --annotation Subset2_Train_35 --output Subset2_Train_35
python preprocess_img.py --i Subset2_Train_15.tiff --annotation Subset2_Train_15 --output Subset2_Train_15
python preprocess_img.py --i Subset2_Train_32.tiff --annotation Subset2_Train_32 --output Subset2_Train_32
python preprocess_img.py --i Subset2_Train_24.tiff --annotation Subset2_Train_24 --output Subset2_Train_24
python preprocess_img.py --i Subset2_Train_28.tiff --annotation Subset2_Train_28 --output Subset2_Train_28
python preprocess_img.py --i Subset2_Train_12.tiff --annotation Subset2_Train_12 --output Subset2_Train_12
python preprocess_img.py --i Subset2_Train_13.tiff --annotation Subset2_Train_13 --output Subset2_Train_13
python preprocess_img.py --i Subset2_Train_29.tiff --annotation Subset2_Train_29 --output Subset2_Train_29
python preprocess_img.py --i Subset2_Train_25.tiff --annotation Subset2_Train_25 --output Subset2_Train_25
python preprocess_img.py --i Subset2_Train_33.tiff --annotation Subset2_Train_33 --output Subset2_Train_33
python preprocess_img.py --i Subset2_Train_26.tiff --annotation Subset2_Train_26 --output Subset2_Train_26
python preprocess_img.py --i Subset2_Train_30.tiff --annotation Subset2_Train_30 --output Subset2_Train_30
python preprocess_img.py --i Subset2_Train_11.tiff --annotation Subset2_Train_11 --output Subset2_Train_11
python preprocess_img.py --i Subset2_Train_31.tiff --annotation Subset2_Train_31 --output Subset2_Train_31
python preprocess_img.py --i Subset2_Train_27.tiff --annotation Subset2_Train_27 --output Subset2_Train_27
python preprocess_img.py --i Subset2_Train_16.tiff --annotation Subset2_Train_16 --output Subset2_Train_16
python preprocess_img.py --i Subset2_Train_20.tiff --annotation Subset2_Train_20 --output Subset2_Train_20
python preprocess_img.py --i Subset2_Train_36.tiff --annotation Subset2_Train_36 --output Subset2_Train_36
python preprocess_img.py --i Subset2_Train_37.tiff --annotation Subset2_Train_37 --output Subset2_Train_37
python preprocess_img.py --i Subset2_Train_21.tiff --annotation Subset2_Train_21 --output Subset2_Train_21
python preprocess_img.py --i Subset2_Train_17.tiff --annotation Subset2_Train_17 --output Subset2_Train_17
