#!/bin/bash
python preprocess_img.py --i Subset1_Train_28.tiff --annotation Subset1_Train_28 --output Subset1_Train_28
python preprocess_img.py --i Subset1_Train_75.tiff --annotation Subset1_Train_75 --output Subset1_Train_75
python preprocess_img.py --i Subset1_Train_94.tiff --annotation Subset1_Train_94 --output Subset1_Train_94
python preprocess_img.py --i Subset1_Train_98.tiff --annotation Subset1_Train_98 --output Subset1_Train_98
python preprocess_img.py --i Subset1_Train_55.tiff --annotation Subset1_Train_55 --output Subset1_Train_55
python preprocess_img.py --i Subset1_Train_81.tiff --annotation Subset1_Train_81 --output Subset1_Train_81
python preprocess_img.py --i Subset1_Train_5.tiff --annotation Subset1_Train_5 --output Subset1_Train_5
python preprocess_img.py --i Subset1_Train_20.tiff --annotation Subset1_Train_20 --output Subset1_Train_20
python preprocess_img.py --i Subset1_Train_40.tiff --annotation Subset1_Train_40 --output Subset1_Train_40
python preprocess_img.py --i Subset1_Train_33.tiff --annotation Subset1_Train_33 --output Subset1_Train_33
python preprocess_img.py --i Subset1_Train_24.tiff --annotation Subset1_Train_24 --output Subset1_Train_24
python preprocess_img.py --i Subset1_Train_56.tiff --annotation Subset1_Train_56 --output Subset1_Train_56
python preprocess_img.py --i Subset1_Train_79.tiff --annotation Subset1_Train_79 --output Subset1_Train_79
python preprocess_img.py --i Subset1_Train_36.tiff --annotation Subset1_Train_36 --output Subset1_Train_36
python preprocess_img.py --i Subset1_Train_6.tiff --annotation Subset1_Train_6 --output Subset1_Train_6
python preprocess_img.py --i Subset1_Train_51.tiff --annotation Subset1_Train_51 --output Subset1_Train_51
python preprocess_img.py --i Subset1_Train_38.tiff --annotation Subset1_Train_38 --output Subset1_Train_38
python preprocess_img.py --i Subset1_Train_90.tiff --annotation Subset1_Train_90 --output Subset1_Train_90
python preprocess_img.py --i Subset1_Train_49.tiff --annotation Subset1_Train_49 --output Subset1_Train_49
python preprocess_img.py --i Subset1_Train_43.tiff --annotation Subset1_Train_43 --output Subset1_Train_43
python preprocess_img.py --i Subset1_Train_85.tiff --annotation Subset1_Train_85 --output Subset1_Train_85
python preprocess_img.py --i Subset1_Train_70.tiff --annotation Subset1_Train_70 --output Subset1_Train_70
python preprocess_img.py --i Subset1_Train_80.tiff --annotation Subset1_Train_80 --output Subset1_Train_80
python preprocess_img.py --i Subset1_Train_52.tiff --annotation Subset1_Train_52 --output Subset1_Train_52
python preprocess_img.py --i Subset1_Train_87.tiff --annotation Subset1_Train_87 --output Subset1_Train_87
python preprocess_img.py --i Subset1_Train_60.tiff --annotation Subset1_Train_60 --output Subset1_Train_60
python preprocess_img.py --i Subset1_Train_99.tiff --annotation Subset1_Train_99 --output Subset1_Train_99
python preprocess_img.py --i Subset1_Train_93.tiff --annotation Subset1_Train_93 --output Subset1_Train_93
python preprocess_img.py --i Subset1_Train_97.tiff --annotation Subset1_Train_97 --output Subset1_Train_97
python preprocess_img.py --i Subset1_Train_44.tiff --annotation Subset1_Train_44 --output Subset1_Train_44
python preprocess_img.py --i Subset1_Train_21.tiff --annotation Subset1_Train_21 --output Subset1_Train_21
python preprocess_img.py --i Subset1_Train_46.tiff --annotation Subset1_Train_46 --output Subset1_Train_46
python preprocess_img.py --i Subset1_Train_88.tiff --annotation Subset1_Train_88 --output Subset1_Train_88
python preprocess_img.py --i Subset1_Train_54.tiff --annotation Subset1_Train_54 --output Subset1_Train_54
python preprocess_img.py --i Subset1_Train_58.tiff --annotation Subset1_Train_58 --output Subset1_Train_58
python preprocess_img.py --i Subset1_Train_25.tiff --annotation Subset1_Train_25 --output Subset1_Train_25
python preprocess_img.py --i Subset1_Train_9.tiff --annotation Subset1_Train_9 --output Subset1_Train_9
python preprocess_img.py --i Subset1_Train_23.tiff --annotation Subset1_Train_23 --output Subset1_Train_23
python preprocess_img.py --i Subset1_Train_74.tiff --annotation Subset1_Train_74 --output Subset1_Train_74
python preprocess_img.py --i Subset1_Train_42.tiff --annotation Subset1_Train_42 --output Subset1_Train_42
python preprocess_img.py --i Subset1_Train_32.tiff --annotation Subset1_Train_32 --output Subset1_Train_32
python preprocess_img.py --i Subset1_Train_31.tiff --annotation Subset1_Train_31 --output Subset1_Train_31
python preprocess_img.py --i Subset1_Train_73.tiff --annotation Subset1_Train_73 --output Subset1_Train_73
python preprocess_img.py --i Subset1_Train_96.tiff --annotation Subset1_Train_96 --output Subset1_Train_96
python preprocess_img.py --i Subset1_Train_22.tiff --annotation Subset1_Train_22 --output Subset1_Train_22
python preprocess_img.py --i Subset1_Train_83.tiff --annotation Subset1_Train_83 --output Subset1_Train_83
python preprocess_img.py --i Subset1_Train_29.tiff --annotation Subset1_Train_29 --output Subset1_Train_29
python preprocess_img.py --i Subset1_Train_41.tiff --annotation Subset1_Train_41 --output Subset1_Train_41
python preprocess_img.py --i Subset1_Train_92.tiff --annotation Subset1_Train_92 --output Subset1_Train_92
python preprocess_img.py --i Subset1_Train_66.tiff --annotation Subset1_Train_66 --output Subset1_Train_66
python preprocess_img.py --i Subset1_Train_65.tiff --annotation Subset1_Train_65 --output Subset1_Train_65
python preprocess_img.py --i Subset1_Train_62.tiff --annotation Subset1_Train_62 --output Subset1_Train_62
python preprocess_img.py --i Subset1_Train_71.tiff --annotation Subset1_Train_71 --output Subset1_Train_71
python preprocess_img.py --i Subset1_Train_86.tiff --annotation Subset1_Train_86 --output Subset1_Train_86
python preprocess_img.py --i Subset1_Train_27.tiff --annotation Subset1_Train_27 --output Subset1_Train_27
python preprocess_img.py --i Subset1_Train_48.tiff --annotation Subset1_Train_48 --output Subset1_Train_48
python preprocess_img.py --i Subset1_Train_26.tiff --annotation Subset1_Train_26 --output Subset1_Train_26
python preprocess_img.py --i Subset1_Train_4.tiff --annotation Subset1_Train_4 --output Subset1_Train_4
python preprocess_img.py --i Subset1_Train_69.tiff --annotation Subset1_Train_69 --output Subset1_Train_69
python preprocess_img.py --i Subset1_Train_95.tiff --annotation Subset1_Train_95 --output Subset1_Train_95
python preprocess_img.py --i Subset1_Train_67.tiff --annotation Subset1_Train_67 --output Subset1_Train_67
python preprocess_img.py --i Subset1_Train_53.tiff --annotation Subset1_Train_53 --output Subset1_Train_53
python preprocess_img.py --i Subset1_Train_91.tiff --annotation Subset1_Train_91 --output Subset1_Train_91
python preprocess_img.py --i Subset1_Train_76.tiff --annotation Subset1_Train_76 --output Subset1_Train_76
python preprocess_img.py --i Subset1_Train_45.tiff --annotation Subset1_Train_45 --output Subset1_Train_45
python preprocess_img.py --i Subset1_Train_57.tiff --annotation Subset1_Train_57 --output Subset1_Train_57
python preprocess_img.py --i Subset1_Train_37.tiff --annotation Subset1_Train_37 --output Subset1_Train_37
python preprocess_img.py --i Subset1_Train_39.tiff --annotation Subset1_Train_39 --output Subset1_Train_39
python preprocess_img.py --i Subset1_Train_82.tiff --annotation Subset1_Train_82 --output Subset1_Train_82
python preprocess_img.py --i Subset1_Train_89.tiff --annotation Subset1_Train_89 --output Subset1_Train_89
python preprocess_img.py --i Subset1_Train_50.tiff --annotation Subset1_Train_50 --output Subset1_Train_50
python preprocess_img.py --i Subset1_Train_34.tiff --annotation Subset1_Train_34 --output Subset1_Train_34
python preprocess_img.py --i Subset1_Train_3.tiff --annotation Subset1_Train_3 --output Subset1_Train_3
python preprocess_img.py --i Subset1_Train_78.tiff --annotation Subset1_Train_78 --output Subset1_Train_78
python preprocess_img.py --i Subset1_Train_35.tiff --annotation Subset1_Train_35 --output Subset1_Train_35
python preprocess_img.py --i Subset1_Train_2.tiff --annotation Subset1_Train_2 --output Subset1_Train_2
python preprocess_img.py --i Subset1_Train_8.tiff --annotation Subset1_Train_8 --output Subset1_Train_8
python preprocess_img.py --i Subset1_Train_72.tiff --annotation Subset1_Train_72 --output Subset1_Train_72
python preprocess_img.py --i Subset1_Train_61.tiff --annotation Subset1_Train_61 --output Subset1_Train_61
python preprocess_img.py --i Subset1_Train_84.tiff --annotation Subset1_Train_84 --output Subset1_Train_84
python preprocess_img.py --i Subset1_Train_7.tiff --annotation Subset1_Train_7 --output Subset1_Train_7
python preprocess_img.py --i Subset1_Train_77.tiff --annotation Subset1_Train_77 --output Subset1_Train_77
python preprocess_img.py --i Subset1_Train_47.tiff --annotation Subset1_Train_47 --output Subset1_Train_47
python preprocess_img.py --i Subset1_Train_59.tiff --annotation Subset1_Train_59 --output Subset1_Train_59
python preprocess_img.py --i Subset1_Train_63.tiff --annotation Subset1_Train_63 --output Subset1_Train_63
python preprocess_img.py --i Subset1_Train_64.tiff --annotation Subset1_Train_64 --output Subset1_Train_64
python preprocess_img.py --i Subset1_Train_68.tiff --annotation Subset1_Train_68 --output Subset1_Train_68
