#!/bin/bash
python preprocess_img.py --i Subset1_Test_40.tiff --annotation Subset1_Test_40 --output Subset1_Test_40
python preprocess_img.py --i Subset1_Test_17.tiff --annotation Subset1_Test_17 --output Subset1_Test_17
python preprocess_img.py --i Subset1_Test_31.tiff --annotation Subset1_Test_31 --output Subset1_Test_31
python preprocess_img.py --i Subset1_Test_26.tiff --annotation Subset1_Test_26 --output Subset1_Test_26
python preprocess_img.py --i Subset1_Test_6.tiff --annotation Subset1_Test_6 --output Subset1_Test_6
python preprocess_img.py --i Subset1_Test_41.tiff --annotation Subset1_Test_41 --output Subset1_Test_41
python preprocess_img.py --i Subset1_Test_21.tiff --annotation Subset1_Test_21 --output Subset1_Test_21
python preprocess_img.py --i Subset1_Test_12.tiff --annotation Subset1_Test_12 --output Subset1_Test_12
python preprocess_img.py --i Subset1_Test_13.tiff --annotation Subset1_Test_13 --output Subset1_Test_13
python preprocess_img.py --i Subset1_Test_18.tiff --annotation Subset1_Test_18 --output Subset1_Test_18
python preprocess_img.py --i Subset1_Test_27.tiff --annotation Subset1_Test_27 --output Subset1_Test_27
python preprocess_img.py --i Subset1_Test_38.tiff --annotation Subset1_Test_38 --output Subset1_Test_38
python preprocess_img.py --i Subset1_Test_33.tiff --annotation Subset1_Test_33 --output Subset1_Test_33
python preprocess_img.py --i Subset1_Test_44.tiff --annotation Subset1_Test_44 --output Subset1_Test_44
python preprocess_img.py --i Subset1_Test_39.tiff --annotation Subset1_Test_39 --output Subset1_Test_39
python preprocess_img.py --i Subset1_Test_9.tiff --annotation Subset1_Test_9 --output Subset1_Test_9
python preprocess_img.py --i Subset1_Test_11.tiff --annotation Subset1_Test_11 --output Subset1_Test_11
python preprocess_img.py --i Subset1_Test_2.tiff --annotation Subset1_Test_2 --output Subset1_Test_2
python preprocess_img.py --i Subset1_Test_7.tiff --annotation Subset1_Test_7 --output Subset1_Test_7
python preprocess_img.py --i Subset1_Test_45.tiff --annotation Subset1_Test_45 --output Subset1_Test_45
python preprocess_img.py --i Subset1_Test_10.tiff --annotation Subset1_Test_10 --output Subset1_Test_10
python preprocess_img.py --i Subset1_Test_37.tiff --annotation Subset1_Test_37 --output Subset1_Test_37
python preprocess_img.py --i Subset1_Test_19.tiff --annotation Subset1_Test_19 --output Subset1_Test_19
python preprocess_img.py --i Subset1_Test_3.tiff --annotation Subset1_Test_3 --output Subset1_Test_3
python preprocess_img.py --i Subset1_Test_8.tiff --annotation Subset1_Test_8 --output Subset1_Test_8
python preprocess_img.py --i Subset1_Test_1.tiff --annotation Subset1_Test_1 --output Subset1_Test_1
python preprocess_img.py --i Subset1_Test_28.tiff --annotation Subset1_Test_28 --output Subset1_Test_28
python preprocess_img.py --i Subset1_Test_29.tiff --annotation Subset1_Test_29 --output Subset1_Test_29
python preprocess_img.py --i Subset1_Test_22.tiff --annotation Subset1_Test_22 --output Subset1_Test_22
python preprocess_img.py --i Subset1_Test_23.tiff --annotation Subset1_Test_23 --output Subset1_Test_23
python preprocess_img.py --i Subset1_Test_5.tiff --annotation Subset1_Test_5 --output Subset1_Test_5
python preprocess_img.py --i Subset1_Test_34.tiff --annotation Subset1_Test_34 --output Subset1_Test_34
python preprocess_img.py --i Subset1_Test_20.tiff --annotation Subset1_Test_20 --output Subset1_Test_20
python preprocess_img.py --i Subset1_Test_14.tiff --annotation Subset1_Test_14 --output Subset1_Test_14
python preprocess_img.py --i Subset1_Test_43.tiff --annotation Subset1_Test_43 --output Subset1_Test_43
python preprocess_img.py --i Subset1_Test_15.tiff --annotation Subset1_Test_15 --output Subset1_Test_15
python preprocess_img.py --i Subset1_Test_16.tiff --annotation Subset1_Test_16 --output Subset1_Test_16
python preprocess_img.py --i Subset1_Test_35.tiff --annotation Subset1_Test_35 --output Subset1_Test_35
python preprocess_img.py --i Subset1_Test_24.tiff --annotation Subset1_Test_24 --output Subset1_Test_24
python preprocess_img.py --i Subset1_Test_30.tiff --annotation Subset1_Test_30 --output Subset1_Test_30
python preprocess_img.py --i Subset1_Test_32.tiff --annotation Subset1_Test_32 --output Subset1_Test_32
python preprocess_img.py --i Subset1_Test_36.tiff --annotation Subset1_Test_36 --output Subset1_Test_36
python preprocess_img.py --i Subset1_Test_4.tiff --annotation Subset1_Test_4 --output Subset1_Test_4
python preprocess_img.py --i Subset1_Test_25.tiff --annotation Subset1_Test_25 --output Subset1_Test_25
python preprocess_img.py --i Subset1_Test_42.tiff --annotation Subset1_Test_42 --output Subset1_Test_42
